name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Ensure android project exists (create/repair)
        run: |
          flutter --version
          # regenerate android platform files so Gradle structure is correct
          flutter create --platforms=android --overwrite .

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK (unsigned)
        run: flutter build apk --release --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
